towncrier:
  # database file
  database: towncrier.sqlite

  # title used
  title: "FastMail status"

  # default service status in the index
  default_status: "up"

  # user/password for the admin api
  admin_user: admin
  admin_password: secret

# Don't change these unless you're doing something special
appname: "towncrier"
charset: "UTF-8"
layout: "main"
template: "template_toolkit"
serializer: "JSON"

